default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: DaG09080$
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: linkea

test:
  <<: *default
  database: linkea

production:
  <<: *default
  database: linkea

